version: 2.0

workflows:
  android:
    name: Android Build Workflow
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
    android:
      build_flavor: production
      gradle_task: assembleRelease
      keystore:
        key_alias: your_key_alias
        key_password: your_key_password
        store_password: your_store_password
        store_file: /path/to/your/keystore.jks
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
